### ISSUE TITLE
Example in Slides not working!

### ISSUE THREAD

**Issue by wwwboy** [DarrenN/backbone-demo#1]
Example in Slides at http://furious-sunset-1319.herokuapp.com/slides not working!

**Comment by DarrenN** [comment]
Hey there - seems to be working fine now. The app is powered by heroku and they've been having a lot of issues with the AWS outage 

++ Darren

**Comment by wwwboy** [comment]
I see "Internal Server Error" on the page "We're going to look at a simple photo app backed by a local server & DB"

-----Original Message-----

**Comment by DarrenN** [comment]
If heroku continues to have problems feel free to check out the project and run the local server so you can see it on your local machine

++ Darren
